<a href="https://colab.research.google.com/github/Sf99-lab/Python-Learning/blob/main/Week6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 6 Tasks

**Task1:**

Explore and write what are universal functions in NumPy and then code three examples each for:
1.   Math
2.   Trigonometry
3. Bit Manipulation
4. Comparison
5. Floating point

**Task 2:** Explore the topic of Indexing and Slicing with Numpy and the provide code examples for the following:
1. Indexing with 2-dimensional Arrays
2. Selecting a subset of a 2-dimensional Array's Rows
3. Selecting a subset of a 2-dimensional Array's Columns

**Task 3:** Find the difference between view/shallow copies and deep copies and then provide code examples for:

1. Shallow copies
2. Deep Copies

**Task 4:** Browse the internet for Python's magic commands. In a text cell discuss what they do and then provide code examples of atleast three such commands following the text cell you will write.








# **Universal Functions in numpy**

Universal functions, or **ufuncs**, in NumPy are functions that operate on ndarrays (N-dimensional arrays) in an element-by-element fashion. They support array broadcasting, type casting, and several other standard features, allowing for efficient and fast element-wise operations

In [ ]:
#Math
import numpy as np

#Addition
print(np.add(1.0, 4.0))

#Square root
print(np.sqrt([49, 121, 7]))

#Exponential
print(np.exp([ 0,1,2]))


5.0
[ 7.         11.          2.64575131]
[1.         2.71828183 7.3890561 ]


In [ ]:
#Trigonometry

#Sine function
angles = np.array([0, np.pi/2, np.pi])

print(np.sin(np.pi/2))

#Cosine function
print(np.cos(np.cos(np.pi)))

#Tangent function
print(np.tan(angles))



1.0
0.5403023058681398
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
#Bit Manipulation

x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.bitwise_and(x, y))

#Bitwise OR
print(np.bitwise_or(x, y))

#Right Shift
print(np.right_shift(y, 1))

[0 0 2]
[5 7 7]
[2 2 3]


In [ ]:
#comparison
a = 4
b = 7
#greater
print(np.greater(a, b))

#equal
print(np.equal(a,b))

#less
print(np.less(a,b))

False
False
True


In [ ]:
#Floating point

#Is finite
c = np.array([np.inf, np.nan, 0])
print(np.isfinite(c))

#Is NaN
print(np.isnan(c))

#Floor
d = np.array([1.9, 2.5, 3.7])
print(np.floor(d))


[False False  True]
[False  True False]
[1. 2. 3.]


#**Task2**
**Indexing and Slicing with Numbpy**

NumPy, a powerful numerical computing library in Python, provides flexible ways to access and manipulate elements within arrays. There are two type of indexing in Numpy: Basic Indexing and Advanced Indexing.

**Basic Indexing:**


NumPy arrays can be indexed using the standard Python syntax: *x[obj]*, where *x* is the array, and obj represents the selection.
There are different types of indexing available:

* **Single Element Indexing:**\
  Works like indexing in other Python sequences.

  It’s 0-based, meaning the first element has index 0.

  Negative indices count from the end of the array.

  **Example:**

      x = np.arange(10)

      x[2]  # Returns 2

      x[-2]  # Returns 8


* **Multidimensional Indexing:**\
Here we can use a single set of square brackets for multiple dimensions.

  **Example:**
      x = np.arange(10)
      x.shape = (2, 5)  # Now x is 2-dimensional
      x[1, 3]  # Returns 8
      x[1, -1]  # Returns 9

  If we index with fewer indices than dimensions, we get a subdimensional array.\
  The returned array is a view (not a copy), pointing to the same memory as the original.

  **For Example:**
      x[0]  # Returns a 1-D array: [0, 1, 2, 3, 4]
      x[0][2]  # Returns 2


**Slicing a Numpy array:**\
  Slicing a NumPy array means accessing the subset of the array. i.e taking elements from one given index to another given index.

  * Basic slicing extends Python’s concept of slicing to N dimensions.

  * Syntax: x[i:j:k], where i is the starting index, j is the stopping index, and k is the step (with k ≠ 0).

  * All indices are zero-based.
  Negative indices count from the end of the array.

        For example:
        x = np.arange(10)
        x[2:7:2]  # Returns array([2, 4, 6])







In [ ]:
# 1. Indexing 2 dimensional array
x = np.arange(10)
x.shape = (2, 5) # Now x is 2-dimensional
print(x[1, 3]) # Returns 8
print(x[1, -1] )# Returns 9


8
9


In [ ]:
# 2. Selecting a subset of a 2-dimensional Array's Rows
x = np.arange(10)
x.shape = (2, 5) # Now x is 2-dimensional
print('2-D array: \n', x)
selected_row = x[1]
print('Selected row: \n',selected_row)

2-D array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Selected row: 
 [5 6 7 8 9]


In [ ]:
# 3. Selecting a subset of a 2-dimensional Array's Columns
x = np.arange(10)
x.shape = (2, 5) # Now x is 2-dimensional
print('2-D array: \n',x)
selected_columns = x[:, 2:5]
print('Selected columans:\n',selected_columns)


2-D array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Selected columans:
 [[2 3 4]
 [7 8 9]]


#**Task 3**

**View/Shallow Copies Vs Deep Copies**

A deep copy and a shallow copy are two ways of creating a new object that has the same data as an existing object. The difference is how they handle references to other objects that the original object may contain.

**View/Shallow Copy**\
A shallow copy only copies the references to other objects, not the objects themselves. This means that the new object and the original object share the same references, and any changes made to one will affect the other.

**Deep copy**\
A deep copy copies the references and the objects they point to. This means that the new object and the original object have independent copies of their data, and any changes made to one will not affect the other.
A deep copy is slower and uses more memory, but it avoids the problems of shared references.

In [ ]:
import copy

# A class that contains a list of colors
class Car:
  def __init__(self, name, colors):
    self.name = name
    self.colors = colors

# Create an object with some data
honda = Car("Honda", ["Red", "Blue"])

# Make a shallow copy of the object
shallow_copy = copy.copy(honda)

# Make a deep copy of the object
deep_copy = copy.deepcopy(honda)

# Modify the list of colors in the original object
honda.colors.append("Green")

# Print the list of colors in each object
print("Original:", honda.colors)
print("Shallow copy:", shallow_copy.colors)
print("Deep copy:", deep_copy.colors)

Original: ['Red', 'Blue', 'Green']
Shallow copy: ['Red', 'Blue', 'Green']
Deep copy: ['Red', 'Blue']


#**Task 4**

**Python's Magic Commands**

Python's magic commands (also known as magic methods or dunder methods) are special commands built into the IPython kernel that make it easy to perform specific tasks. These commands enhance Python’s capabilities by allowing interactions with the operating system, other programming languages, or different kernels. There are two main categories of magic commands:

**1. Line Magics:**

* Denoted by a single % prefix.

*   Operate on a single line of input.
*   Commonly used for quick tasks or modifications.
           Example: %run, %timeit, %load, %pwd, etc.

**2. Cell Magics:**

* Denoted by a double %% prefix.
* Operate on multiple lines of input (an entire cell).
* Useful for more complex operations.
       Example: %%writefile, %%sql, %%bash, etc.








In [ ]:
# Prints the current working directory.

%pwd



'/content'

In [ ]:
# Lists the contents of the current directory.
%ls



sample_data/


In [ ]:
# Measure the execution time of a single Python statement or expression.
from timeit import timeit
%timeit L = [n ** 2 for n in range(1000)]
print(L)


305 µs ± 8.89 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
3.016489098999955
